controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
test:
  path: /test
  controller: App\Controller\testController::index
test1:
  path: /test2
  controller: App\Controller\testController::test2
